# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc ""
  homepage "https://github.com/josa42/run"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d5a6fc5b83e5fef95477fcea485e00b63e4f58a043686820dfa20d5f65212244"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Darwin_arm64.tar.gz"
      sha256 "df35c73ead687b48adf01a0b0ce7331a5de2670b896252fa7177787f73090609"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cff83827a55eb630f187e8788b973f82b9f278bea81ce7dffd3fcc3f468e4f77"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Linux_arm64.tar.gz"
      sha256 "6e53ac0dd4412869fd056f437e725f9065082807f7933e867023a604c784a5b2"

      def install
        bin.install "run"
      end
    end
  end

  depends_on "go" => :build
end
