# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc ""
  homepage "https://github.com/josa42/run"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "164b2bcc39fbfc7e0b4ce06f07b38ea33241b8429b42c23d838ac56a7ff0b563"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c72c5180b7accc7c9a1be57575798469d928524239db72d392996d5353c16d26"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Linux_arm64.tar.gz"
      sha256 "fe98df754bfd24ba29640ccfc331ddbab765ded091471f805812caf4ccc2472d"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/josa42/run/releases/download/v0.1.0/run_0.1.0_Linux_x86_64.tar.gz"
      sha256 "ee03e141f05293ca0c2d290debb37196c6b8bf78b270908f8a87fdab8440fdff"

      def install
        bin.install "run"
      end
    end
  end

  depends_on "go" => :build
end
